import { Transaction } from './types';

export const APP_NAME = "ghifarmkcy";

export const DEFAULT_CATEGORIES = [
  "Housing",
  "Food",
  "Transportation",
  "Utilities",
  "Entertainment",
  "Healthcare",
  "Salary",
  "Freelance",
  "Investment",
  "Other"
];

// For backward compatibility if imported elsewhere, but we prefer dynamic keys now
export const CATEGORIES = DEFAULT_CATEGORIES;

export const EXCHANGE_RATES = {
  USD: 1,
  EUR: 0.92,
  IDR: 16000
};

// More realistic seed data spanning multiple months
export const INITIAL_TRANSACTIONS: Transaction[] = [
  // October
  { id: '1', amount: 5400, description: 'Client Project Payment', category: 'Freelance', type: 'income', date: '2023-10-01', created_at: new Date().toISOString() },
  { id: '2', amount: 1200, description: 'Monthly Rent', category: 'Housing', type: 'expense', date: '2023-10-02', created_at: new Date().toISOString() },
  { id: '3', amount: 150, description: 'Grocery Run', category: 'Food', type: 'expense', date: '2023-10-05', created_at: new Date().toISOString() },
  { id: '4', amount: 3200, description: 'Monthly Salary', category: 'Salary', type: 'income', date: '2023-10-15', created_at: new Date().toISOString() },
  { id: '5', amount: 60, description: 'Netflix & Spotify', category: 'Entertainment', type: 'expense', date: '2023-10-18', created_at: new Date().toISOString() },
  { id: '6', amount: 200, description: 'Electricity Bill', category: 'Utilities', type: 'expense', date: '2023-10-20', created_at: new Date().toISOString() },
  { id: '7', amount: 850, description: 'Car Maintenance', category: 'Transportation', type: 'expense', date: '2023-10-22', created_at: new Date().toISOString() },
  
  // September
  { id: '8', amount: 3200, description: 'Monthly Salary', category: 'Salary', type: 'income', date: '2023-09-15', created_at: new Date().toISOString() },
  { id: '9', amount: 1200, description: 'Monthly Rent', category: 'Housing', type: 'expense', date: '2023-09-02', created_at: new Date().toISOString() },
  { id: '10', amount: 400, description: 'Weekend Trip', category: 'Entertainment', type: 'expense', date: '2023-09-10', created_at: new Date().toISOString() },
  { id: '11', amount: 300, description: 'Grocery Run', category: 'Food', type: 'expense', date: '2023-09-05', created_at: new Date().toISOString() },

  // August
  { id: '12', amount: 3200, description: 'Monthly Salary', category: 'Salary', type: 'income', date: '2023-08-15', created_at: new Date().toISOString() },
  { id: '13', amount: 1800, description: 'New Laptop', category: 'Other', type: 'expense', date: '2023-08-20', created_at: new Date().toISOString() },
  { id: '14', amount: 1200, description: 'Monthly Rent', category: 'Housing', type: 'expense', date: '2023-08-02', created_at: new Date().toISOString() },
];

export const TRANSLATIONS = {
  en: {
    overview: "Overview",
    transactions: "Transactions",
    budgeting: "Budgeting",
    settings: "Settings",
    totalBalance: "Total Balance",
    availableFunds: "Available funds",
    income: "Income",
    expenses: "Expenses",
    savingsRate: "Savings Rate",
    cashFlow: "Cash Flow Overview",
    topSpending: "Top Spending",
    recentTransactions: "Recent Transactions",
    addTransaction: "Add Transaction",
    adding: "Adding...",
    quickAdd: "Quick Add",
    saveChanges: "Save Changes",
    saving: "Saving...",
    displayName: "Display Name",
    email: "Email",
    password: "Password",
    currency: "Currency",
    language: "Language",
    smartBudgeting: "Smart Budgeting",
    budgetDesc: "Set limits and track your spending goals by category.",
    monthlyLimit: "Monthly Limit",
    dailyTarget: "Daily Target",
    welcome: "Welcome back, here's what's happening today.",
    manageTx: "Manage and track all your income and expenses.",
    trackBudget: "Keep your spending on track with category limits.",
    managePref: "Manage your profile and application preferences.",
    signOut: "Sign Out",
    accountSettings: "Account Settings",
    preferences: "Preferences",
    vsLastMonth: "vs last month",
    target: "Target",
    noTx: "No transactions found within this date range.",
    manageBudget: "Manage Budget",
    cancel: "Cancel",
    saveBudget: "Save Limits",
    dailySafe: "Daily Safe Spend",
    projected: "Projected Spend",
    daysLeft: "days left",
    budgetStatus: "Budget Status",
    onTrack: "On Track",
    atRisk: "At Risk",
    overBudget: "Over Budget",
    addCategory: "Add Category",
    newCategoryName: "New Category Name",
    delete: "Delete",
    pickDate: "Pick a date range",
    filteredBy: "Filtered by",
    // Auth
    loginTitle: "Welcome back",
    loginDesc: "Enter your credentials to access your account.",
    registerTitle: "Create an account",
    registerDesc: "Enter your email below to create your account.",
    signIn: "Sign In",
    signUp: "Sign Up",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    // Onboarding
    welcomeSetup: "Welcome to ghifarmkcy",
    setupDesc: "Let's set up your profile to get started.",
    stepLang: "First, select your language",
    step1: "What should we call you?",
    step2: "Select your currency",
    step3: "What is your monthly budget goal?",
    next: "Next",
    back: "Back",
    finish: "Finish Setup",
    namePlaceholder: "e.g. Ghifar",
    budgetPlaceholder: "Total monthly spending limit",
    // Tour
    tourConfirmTitle: "Quick Tour?",
    tourConfirmDesc: "Would you like a quick tour of the features?",
    startTour: "Start Tour",
    skipTour: "Skip",
    tourBalanceTitle: "Total Balance",
    tourBalanceDesc: "See your real-time financial health here.",
    tourQuickAddTitle: "Quick Add",
    tourQuickAddDesc: "Easily record new income or expenses in seconds.",
    tourFilterTitle: "Date Filter",
    tourFilterDesc: "Analyze your spending history by specific dates.",
    // New Balance & Savings
    setInitialBalance: "Set Initial Balance",
    initialBalanceDesc: "This amount will be added to your calculated income/expenses.",
    save: "Save",
    noIncome: "No Income Data",
    excellent: "Excellent",
    good: "Good",
    needsWork: "Needs Work"
  },
  id: {
    overview: "Ringkasan",
    transactions: "Transaksi",
    budgeting: "Anggaran",
    settings: "Pengaturan",
    totalBalance: "Total Saldo",
    availableFunds: "Dana tersedia",
    income: "Pemasukan",
    expenses: "Pengeluaran",
    savingsRate: "Tingkat Tabungan",
    cashFlow: "Arus Kas",
    topSpending: "Pengeluaran Terbesar",
    recentTransactions: "Transaksi Terkini",
    addTransaction: "Tambah Transaksi",
    adding: "Menambahkan...",
    quickAdd: "Tambah Cepat",
    saveChanges: "Simpan Perubahan",
    saving: "Menyimpan...",
    displayName: "Nama Tampilan",
    email: "Email",
    password: "Kata Sandi",
    currency: "Mata Uang",
    language: "Bahasa",
    smartBudgeting: "Anggaran Pintar",
    budgetDesc: "Tetapkan batas dan pantau tujuan pengeluaran Anda per kategori.",
    monthlyLimit: "Batas Bulanan",
    dailyTarget: "Target Harian",
    welcome: "Selamat datang kembali, ini ringkasan hari ini.",
    manageTx: "Kelola dan pantau semua pemasukan dan pengeluaran Anda.",
    trackBudget: "Jaga pengeluaran Anda tetap sesuai dengan batas kategori.",
    managePref: "Kelola profil dan preferensi aplikasi Anda.",
    signOut: "Keluar",
    accountSettings: "Pengaturan Akun",
    preferences: "Preferensi",
    vsLastMonth: "vs bulan lalu",
    target: "Target",
    noTx: "Tidak ada transaksi ditemukan dalam rentang tanggal ini.",
    manageBudget: "Kelola Anggaran",
    cancel: "Batal",
    saveBudget: "Simpan Batas",
    dailySafe: "Batas Harian Aman",
    projected: "Proyeksi Pengeluaran",
    daysLeft: "hari tersisa",
    budgetStatus: "Status Anggaran",
    onTrack: "Aman",
    atRisk: "Berisiko",
    overBudget: "Melebihi Batas",
    addCategory: "Tambah Kategori",
    newCategoryName: "Nama Kategori Baru",
    delete: "Hapus",
    pickDate: "Pilih rentang tanggal",
    filteredBy: "Difilter berdasarkan",
    // Auth
    loginTitle: "Selamat Datang Kembali",
    loginDesc: "Masukkan kredensial Anda untuk masuk.",
    registerTitle: "Buat Akun",
    registerDesc: "Masukkan email di bawah untuk mendaftar.",
    signIn: "Masuk",
    signUp: "Daftar",
    noAccount: "Belum punya akun?",
    hasAccount: "Sudah punya akun?",
    // Onboarding
    welcomeSetup: "Selamat datang di ghifarmkcy",
    setupDesc: "Mari atur profil Anda untuk memulai.",
    stepLang: "Pertama, pilih bahasa Anda",
    step1: "Siapa nama panggilan Anda?",
    step2: "Pilih mata uang Anda",
    step3: "Berapa target anggaran bulanan Anda?",
    next: "Lanjut",
    back: "Kembali",
    finish: "Selesai",
    namePlaceholder: "cth. Ghifar",
    budgetPlaceholder: "Total batas pengeluaran bulanan",
    // Tour
    tourConfirmTitle: "Tur Singkat?",
    tourConfirmDesc: "Apakah Anda ingin tur singkat fitur aplikasi?",
    startTour: "Mulai Tur",
    skipTour: "Lewati",
    tourBalanceTitle: "Total Saldo",
    tourBalanceDesc: "Lihat kesehatan keuangan real-time Anda di sini.",
    tourQuickAddTitle: "Tambah Cepat",
    tourQuickAddDesc: "Catat pemasukan atau pengeluaran baru dengan mudah.",
    tourFilterTitle: "Filter Tanggal",
    tourFilterDesc: "Analisis riwayat pengeluaran Anda berdasarkan tanggal tertentu.",
    // New Balance & Savings
    setInitialBalance: "Atur Saldo Awal",
    initialBalanceDesc: "Jumlah ini akan ditambahkan ke perhitungan pemasukan/pengeluaran Anda.",
    save: "Simpan",
    noIncome: "Belum Ada Pemasukan",
    excellent: "Sangat Baik",
    good: "Baik",
    needsWork: "Perlu Perbaikan"
  }
};